/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface":               "#dfe3e6",
        "surface":                  "#0A1931",
        "surface-container-lowest": "#050d1a",
        "surface-container-low":    "#1A3D63",
        "surface-container":        "#1A3D63",
        "surface-container-high":   "#234d7a",
        "surface-container-highest":"#2c5685",
        "surface-bright":           "#234d7a",
        "surface-dim":              "#0A1931",
        "background":               "#0A1931",
        "on-background":            "#dfe3e6",
        "primary":                  "#B3CFE5",
        "on-primary":               "#0A1931",
        "primary-container":        "#B3CFE5",
        "on-primary-container":     "#3e596b",
        "primary-fixed":            "#cae6fd",
        "primary-fixed-dim":        "#B3CFE5",
        "secondary":                "#4A7FA7",
        "on-secondary":             "#003450",
        "secondary-container":      "#1A3D63",
        "on-secondary-container":   "#8abee9",
        "secondary-fixed":          "#cbe6ff",
        "secondary-fixed-dim":      "#4A7FA7",
        "tertiary":                 "#dbe8ff",
        "on-tertiary":              "#0a3157",
        "tertiary-container":       "#aecefc",
        "on-tertiary-container":    "#37577f",
        "tertiary-fixed":           "#d3e4ff",
        "tertiary-fixed-dim":       "#a9c9f6",
        "error":                    "#ffb4ab",
        "on-error":                 "#690005",
        "error-container":          "#93000a",
        "on-error-container":       "#ffdad6",
        "outline":                  "#8c9196",
        "outline-variant":          "#4A7FA7",
        "on-surface-variant":       "#c2c7cc",
        "surface-variant":          "#1A3D63",
        "inverse-surface":          "#dfe3e6",
        "inverse-on-surface":       "#2c3134",
        "inverse-primary":          "#476274",
        "surface-tint":             "#B3CFE5",
        "accent-primary":           "#4A7FA7",
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile":  "16px",
        "gutter":         "24px",
        "stack-sm":       "8px",
        "stack-md":       "16px",
        "stack-lg":       "32px",
      },
      fontFamily: {
        "display":       ["Hanken Grotesk", "sans-serif"],
        "headline-lg":   ["Hanken Grotesk", "sans-serif"],
        "headline-md":   ["Hanken Grotesk", "sans-serif"],
        "body-lg":       ["Inter", "sans-serif"],
        "body-md":       ["Inter", "sans-serif"],
        "body-sm":       ["Inter", "sans-serif"],
        "label-lg":      ["Inter", "sans-serif"],
        "label-sm":      ["Inter", "sans-serif"],
        "mono-sm":       ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display":      ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":  ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md":  ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg":      ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":      ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm":      ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg":     ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm":     ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "mono-sm":      ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
