"""
search.py — FAISS-based historical disaster retrieval.

Loads the prebuilt FAISS index and metadata once on first call,
then answers top-k cosine similarity queries against the
historical disaster event database.

Usage
-----
    from retrieval.search import find_similar_events
    results = find_similar_events("/tmp/query.jpg", top_k=5)

Index files (generated by build_index.py)
-----------------------------------------
    datasets/historical/index/disaster.index   — FAISS IndexFlatIP
    datasets/historical/index/metadata.json    — ordered list of event dicts

Hardening changes:
  Fix H — Minimum similarity threshold of 40%.  Events whose cosine
           similarity to the query is below this threshold are silently
           excluded.  If no events exceed the threshold an empty list is
           returned, preventing misleading low-quality matches from being
           shown to users.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path

import faiss
import numpy as np

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT       = Path(__file__).resolve().parent.parent.parent
_INDEX_PATH = _ROOT / "datasets" / "historical" / "index" / "disaster.index"
_META_PATH  = _ROOT / "datasets" / "historical" / "index" / "metadata.json"

# ---------------------------------------------------------------------------
# Lazy singleton index
# ---------------------------------------------------------------------------

_index:    faiss.IndexFlatIP | None = None
_metadata: list[dict]               = []
_lock      = threading.Lock()
_ready     = False          # True only when both index + metadata are loaded

# Fix H — Minimum cosine similarity (as a 0–100 percentage) to include a result.
# Events below this threshold are discarded even if they are the "best" matches.
_MIN_SIMILARITY_PCT: float = 40.0


def _load_index() -> bool:
    """Load FAISS index and metadata. Returns True if index is available."""
    global _index, _metadata, _ready

    if _ready:
        return True

    with _lock:
        if _ready:
            return True

        if not _INDEX_PATH.exists() or not _META_PATH.exists():
            logger.warning(
                "[Retrieval] Index not found at %s. "
                "Run scripts/build_historical_index.py first.",
                _INDEX_PATH,
            )
            return False

        try:
            _index    = faiss.read_index(str(_INDEX_PATH))
            _metadata = json.loads(_META_PATH.read_text(encoding="utf-8"))
            _ready    = True
            logger.info(
                "[Retrieval] Index loaded: %d events, dim=%d",
                _index.ntotal,
                _index.d,
            )
            return True
        except Exception as exc:
            logger.error("[Retrieval] Failed to load index: %s", exc)
            return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def find_similar_events(
    image_path: str,
    top_k: int = 5,
    category_filter: str | None = None,
) -> list[dict]:
    """
    Find the top-k most visually similar historical disaster events.

    Args:
        image_path      : Path to the query image file.
        top_k           : Number of results to return (default 5).
        category_filter : If set (e.g. "flood"), restrict results to that
                          category. Achieved by over-fetching and filtering.

    Returns:
        List of dicts, each with keys:
            event, year, location, category, description,
            similarity (0–100, float), casualties, affected_population
        Ordered by descending similarity.
        Returns [] if the index is not built yet.
    """
    if not _load_index():
        return []

    # Import here so we don't pull CLIP into scope until needed.
    import sys
    _SRC = Path(__file__).resolve().parent.parent
    if str(_SRC) not in sys.path:
        sys.path.insert(0, str(_SRC))

    from models.clip_model import embed_image

    try:
        query_vec = embed_image(image_path).reshape(1, -1)  # (1, 512)
    except Exception as exc:
        logger.error("[Retrieval] Embedding failed: %s", exc)
        return []

    logger.info(
        "[Retrieval] Embedding OK — norm=%.4f  filter=%r  index_ntotal=%d  meta_len=%d",
        float((query_vec ** 2).sum() ** 0.5),
        category_filter,
        _index.ntotal,
        len(_metadata),
    )

    # Over-fetch if filtering by category so we can still return top_k after
    fetch_k = top_k * 5 if category_filter else top_k

    distances, indices = _index.search(query_vec, min(fetch_k, _index.ntotal))

    logger.info(
        "[Retrieval] FAISS returned %d hits — top3_dist=%s  top3_idx=%s",
        len(distances[0]),
        list(distances[0][:3]),
        list(indices[0][:3]),
    )

    results: list[dict] = []
    for dist, idx in zip(distances[0], indices[0]):
        if idx < 0 or idx >= len(_metadata):
            logger.warning("[Retrieval] Skipping invalid idx=%d (meta_len=%d)", idx, len(_metadata))
            continue

        event = _metadata[idx]

        if category_filter and event.get("category", "").lower() != category_filter.lower():
            continue

        # IndexFlatIP with normalised vectors: dist == cosine similarity in [-1, 1]
        similarity = round(float(dist) * 100, 1)

        # Fix H — discard low-quality matches below the minimum threshold
        if similarity < _MIN_SIMILARITY_PCT:
            logger.debug(
                "[Retrieval] Skipping event '%s' — similarity %.1f%% < threshold %.1f%%",
                event.get("name", "?"), similarity, _MIN_SIMILARITY_PCT,
            )
            continue

        results.append({
            "event":                event.get("name", "Unknown Event"),
            "year":                 event.get("year"),
            "location":             event.get("location", ""),
            "category":             event.get("category", ""),
            "description":          event.get("description", ""),
            "similarity":           similarity,
            "casualties":           event.get("casualties"),
            "affected_population":  event.get("affected_population", ""),
            "damage_usd_billion":   event.get("damage_usd_billion"),
            "source":               event.get("source", ""),
        })

        if len(results) >= top_k:
            break

    if not results:
        logger.info(
            "[Retrieval] No events exceeded %.0f%% similarity threshold — returning []",
            _MIN_SIMILARITY_PCT,
        )
    return results


def index_status() -> dict:
    """Return the current state of the FAISS index for health checks."""
    loaded = _load_index()
    return {
        "index_built":   loaded,
        "event_count":   _index.ntotal if loaded and _index else 0,
        "index_path":    str(_INDEX_PATH),
        "metadata_path": str(_META_PATH),
    }
